# -*- coding: utf-8 -*-
"""Code used for scrapping tweets

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D8hj6Yl19-rMx-exzPrMJj1a3pmFu3ZR
"""

pip install snscrape

pip install datetime

pip install pandas

import snscrape.modules.twitter as sntwitter
import pandas as pd
import datetime

query = "(#PrayersForTurkey OR #"Powerful OR #7.8" OR #Turkish OR #earthquakeinturkey OR #هزة_أرضية) lang:en since:2023-02-06"
tweets = []
limit = 1000000

for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        time = tweet.date.time()
        tweets.append([tweet.date, time, tweet.user.username, tweet.content])

df = pd.DataFrame(tweets, columns=['Date', 'Time', 'user', 'Tweet'])

df.to_csv('turkey.csv')

